# Generated by Django 4.0.6 on 2022-07-15 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('due', models.DateField(verbose_name='Due Date')),
                ('description', models.TextField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('LOW', 'Low Priority'), ('MID', 'Medium Priority'), ('HIGH', 'High Priority'), ('EMERG', 'EMERGENCY PRIORITY!')], default='LOW', max_length=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization'),
        ),
    ]
