# Generated by Django 4.0.6 on 2022-07-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dep',
        ),
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.ManyToManyField(to='main_app.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='task',
            field=models.ManyToManyField(to='main_app.task'),
        ),
    ]
