# Generated by Django 4.0.6 on 2022-07-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_organization_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('AS', 'Assigned'), ('UAS', 'Unassigned'), ('COM', 'Complete')], default='IP', max_length=3),
        ),
    ]
